language: clojure

before_install:
  - npm install -g karma
  - npm install -g karma-cljs-test
  - npm install -g karma-firefox-launcher

script:
  - lein figtest-dom-travis
  - lein figtest-nodom-travis
  - lein doo firefox-headless test-dom once
  - lein doo firefox-headless test-nodom once
