name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add pwd to PATH
      shell: bash
      run: echo "$(pwd)" >> "$GITHUB_PATH"
    - name: Install Leiningen
      shell: bash
      run: |
        curl -LSs https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o lein
        chmod +x lein
    - name: Install karma
      run: sudo npm install -g karma karma-cljs-test karma-firefox-launcher karma-chrome-launcher
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: |
        lein doo firefox-headless test-dom once
        lein doo firefox-headless test-nodom once
    - name: Notify with mattermost upon failure
      if: failure()
      env:
        SECRET: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        CHANNEL: "reacl"
        USERNAME: "GitHub"
      run: |
        URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
        curl -i --data-urlencode "payload={\"channel\":\"${CHANNEL}\", \"username\":\"${USERNAME}\",\"text\":\"Failure in tests: ${URL}\"}" ${SECRET}
